<!--
  -- Guusnara Customs Decrypt v2.1
  -- http://guusnara.com/
  --
  -- Copyright 2013 Guusnara
  --
  -- Date: 2013-09-19T16:25Z
  --
  -- DON'T EDIT THIS SCRIPT!
-->
<?php function guus_decrypt($password){$guus_input=@$password;$guus_totals=strlen($guus_input);$guus_ceiling=ceil($guus_totals/2);$guus_setting_part1=substr($guus_input,0,$guus_ceiling);$guus_setting_part2=substr($guus_input,$guus_ceiling,$guus_totals-$guus_ceiling);$guus_output=md5(md5(strtolower(base64_encode(sha1($guus_setting_part1)))).md5(sha1(md5(strtolower(base64_encode($guus_setting_part2))))));$guus_netral_input=strtolower($guus_output);$guus_netral_input_lenght=strlen($guus_netral_input);for($i=1;$i<=$guus_netral_input_lenght;$i++){if($i==$guus_netral_input_lenght){$guus_netral_finalsort=substr($guus_netral_input,$guus_netral_input_lenght-1,1);}else{$guus_netral_sort=substr($guus_netral_input,0,$i-$guus_netral_input_lenght);$guus_netral_min=$guus_netral_input_lenght-strlen($guus_netral_sort);$guus_netral_finalsort=substr($guus_netral_input,$i-1,-$guus_netral_min);}switch($guus_netral_finalsort){case'0':$guus_netral_output=str_replace($guus_netral_finalsort,'z',$guus_netral_finalsort);break;case'1':$guus_netral_output=str_replace($guus_netral_finalsort,'p',$guus_netral_finalsort);break;case'2':$guus_netral_output=str_replace($guus_netral_finalsort,'y',$guus_netral_finalsort);break;case'3':$guus_netral_output=str_replace($guus_netral_finalsort,'d',$guus_netral_finalsort);break;case'4':$guus_netral_output=str_replace($guus_netral_finalsort,'e',$guus_netral_finalsort);break;case'5':$guus_netral_output=str_replace($guus_netral_finalsort,'f',$guus_netral_finalsort);break;case'6':$guus_netral_output=str_replace($guus_netral_finalsort,'b',$guus_netral_finalsort);break;case'7':$guus_netral_output=str_replace($guus_netral_finalsort,'a',$guus_netral_finalsort);break;case'8':$guus_netral_output=str_replace($guus_netral_finalsort,'c',$guus_netral_finalsort);break;case'9':$guus_netral_output=str_replace($guus_netral_finalsort,'q',$guus_netral_finalsort);break;case'a':$guus_netral_output='a';break;case'b':$guus_netral_output='b';break;case'c':$guus_netral_output='c';break;case'd':$guus_netral_output='d';break;case'e':$guus_netral_output='e';break;case'f':$guus_netral_output='f';break;case 'g':$guus_netral_output='g';break;case'h':$guus_netral_output='h';break;case'i':$guus_netral_output='i';break;case'j':$guus_netral_output='j';break;case'k':$guus_netral_output='k';break;case'l':$guus_netral_output='l';break;case'm':$guus_netral_output='m';break;case'n':$guus_netral_output='n';break;case'o':$guus_netral_output='o';break;case'p':$guus_netral_output='p';break;case'q':$guus_netral_output='q';break;case'r':$guus_netral_output='r';break;case's':$guus_netral_output='s';break;case't':$guus_netral_output='t';break;case'u':$guus_netral_output='u';break;case 'v':$guus_netral_output='v';break;case'w':$guus_netral_output='w';break;case'x':$guus_netral_output='x';break;case'y':$guus_netral_output='y';break;case'z':$guus_netral_output='z';break;}@$guus_netral_return.=$guus_netral_output;}return $guus_netral_return;}?>